# image: alpine:latest
stages:
  - deploy

before_script:
  - apk update
  - apk add --no-cache openssh  # Install OpenSSH package to get ssh-keyscan
  - mkdir -p ~/.ssh
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-keyscan -H 34.77.95.113 >> ~/.ssh/known_hosts

deploy:
  stage: deploy
  script:
    - echo "Starting deployment..."
    - ssh -o StrictHostKeyChecking=no grpc@34.77.95.113 "cd $REMOTE_PATH && git pull && pm2 restart all"
  rules:
   - if: '$CI_COMMIT_REF_NAME == "GS-1-gRPC-services"'
