stages:
  - deploy
  - test

###Actions As Functions 

.gcp_configuration: &gcp_configuration
  - echo "$GOOGLE_CLOUD_CREDENTIALS" > gcloud-service-key.json
  - gcloud auth activate-service-account --key-file gcloud-service-key.json
  - gcloud config set project $FIREBASE_PROJECT_ID

.deploy_cloud_run: &deploy_cloud_run
  - gcloud builds submit --tag $GITLAB_IMAGE_TAG
  - cat $CLOUD_RUN_ENV
  - python3 $JOIN_ENVS_PY $CLOUD_RUN_ENV $CLOUD_RUN_ENVS_MAIN > .env.yaml
  - gcloud run services update $CLOUD_RUN_SERVICE_ID-svc-grpc  --image $GITLAB_IMAGE_TAG --env-vars-file=.env.yaml --region=$CLOUD_RUN_REGION --platform managed --port=$CLOUD_RUN_PORT


### Templates

.deploy_template:
  stage: deploy
  image: google/cloud-sdk:471.0.0
  environment:
    name: $CI_COMMIT_BRANCH
  variables:
    GITLAB_IMAGE_TAG: gcr.io/$FIREBASE_PROJECT_ID/$CLOUD_RUN_SERVICE_ID/$CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
    GOOGLE_APPLICATION_CREDENTIALS: $GOOGLE_CLOUD_CREDENTIALS
    FIREBASE_PROJECT_ID: $FIREBASE_PROJECT_ID
#############################Actiond/Conditions#####################

deploy_dev:
  extends: .deploy_template

  rules:
    - if: $CI_COMMIT_BRANCH == 'GS-1-gRPC-services'
  before_script:
    - *gcp_configuration
  script:
    - *deploy_cloud_run

    
